Meta:
  description: Custom config for assembled form.
Inputs:
  formCustomVersion:
    name: formCustomVersion
    type: hidden
    value: "[MC2_DLS_Apr_2023]"
    form: dsp

Checklist:
  items:
    - name: Provide project info & contacts
    - name: Specify resources to be shared
    - name: Submit this form
    
